name: Test
"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install
        run: npm ci
      - name: Check JS
        run: npx -p typescript tsc --allowJs --noEmit --lib es2020 *.js
      - name: Test
        run: npm test
